### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by stevetoro** [teampique/prj-rev-bwfs-dasmoto#7]
https://github.com/teampique/prj-rev-bwfs-dasmoto/blob/master/Arts%20and%20Crafts/Resources/css/style.css#L15-L39

You're repeating a lot of styles in the `#brushes`, `#frames`, and `#paint` rules. Consolidate the shared styles into a single rule:

```css
#brushes, #frames, #paint {
  color: white;
  font-weight: bold;
  font-size: 32px;
}
```
